services:
  backend:
    build: ./backend
    container_name: splithappens-backend
    environment:
      SPRING_PROFILES_ACTIVE: dev
      DATABASE_URL: ${DATABASE_URL}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
    ports:
      - "8080:8080"
    networks:
      - splithappens-network

  frontend:
    build:
      context: ./frontend
      args:
        - VITE_BE_URL=${VITE_BE_URL}
    container_name: splithappens-frontend
    ports:
      - "5173:80"
    networks:
      - splithappens-network

networks:
  splithappens-network:
    driver: bridge