package cz.splithappens.model.enums;

public enum NotificationType {
    EXPENSE_ADDED,
    EXPENSE_ADDED_FRIEND,
    DEBT_SETTLED,
    DEBT_SETTLED_FRIEND,
    DEBT_NOTIFIED,
    DEBT_NOTIFIED_FRIEND,
    ADDED_TO_GROUP,
    RECEIVED_FRIEND_REQUEST,
    ACCEPTED_FRIEND_REQUEST,
    REJECTED_FRIEND_REQUEST,
}

