spring.application.name=splithappens-backend
server.port=8080

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://ep-cold-snow-agtfba9z-pooler.c-2.eu-central-1.aws.neon.tech/splithappens?sslmode=require&channel_binding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_0pYMmBTe8ALi

# JPA / Hibernate settings
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/db.changelog.yaml